# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rFCYZ9OCFdIXRUf6l_DRkwqy81tJo2N7
"""

from stt import speech_to_text
from emotion import get_emotion
from bot import func1
from bot import func2
from tts import text_to_speech
from IPython.display import Audio, display

audio_files = ["path_to_audio"]
personage = "personage_name"
functions = {"wiki": func1, "humor": func2}
for i in audio_files:
    enter_prompt = speech_to_text(i)
    emotion = get_emotion(i)
    bot_ans = functions[personage](enter_prompt, emotion)
    audio = text_to_speech(bot_ans)
    display(Audio(audio, rate=48000))